config/routes.rb
Rails.application.routes.draw do
  root 'index#index'

  scope '/session', controller: :user_sessions do
    get :new, as: :new_session
    post :create, as: :create_session
    get :destroy, as: :destroy_session
  end

  get :registration, to: 'users#new', as: :registration
  post :registration, to: 'users#create', as: :register

  namespace :admin do
    resources :games
    resources :accounts do
      member do
        post :add_game
        post 'add_deal/:type', action: :add_deal, as: :add_deal
        delete 'remove_deal/:deal_id', action: :remove_deal, as: :remove_deal
      end
    end
  end

  resources :accounts do
    member do
      get 'buy/:type', action: :buy, as: :buy
    end
  end
  resources :games

end

app/models/account.rb
# Account with games
class Account
  include Mongoid::Document
  include Mongoid::Timestamps

  field :email, type: String
  field :email_password, type: String
  field :password, type: String
  field :birthday, type: Date

  has_and_belongs_to_many :games
  has_many :deals  do
    def by_type(type)
      where(type_cd: type)
    end
  end

  def can_sell?(type)
    deal = last_deal(type)
    deal.nil? || deal.disabled?
  end

  def last_deal(type)
    type = type.to_i
    return nil unless correct_deal_type(type)
    deals.by_type(type).last
  end

  validates :email, email: true, uniqueness: true
  validates_presence_of :email, :email_password, :password

  protected

  def correct_deal_type(type)
    [1, 2, 3].include?(type)
  end
end

app/models/deal.rb
# User buy p1/p2/p3 account
class Deal
  include Mongoid::Document
  include SimpleEnum::Mongoid
  include Mongoid::Timestamps::Created

  belongs_to :account
  belongs_to :user

  field :disabled, type: Boolean, default: false
  field :price, type: Integer

  as_enum :type, p1: 1, p2: 2, p3: 3

  validates :price, numericality: { greater_than_or_equal_to: 0 }

  validates_presence_of :type, :account, :price

  before_validation :check_prev_user
  before_validation :check_prev_enabled
  before_validation :cant_disable_without_user

  before_destroy :dont_destroy_with_user

  def disabled?
    disabled
  end

  def enabled?
    !disabled?
  end

  def prev_deal
    same_deal.lt(created_at: created_at || Time.now).order_by(created_at: :desc).first
  end

  def next_deal
    return if new_record?
    same_deal.gt(created_at: created_at).order_by(created_at: :asc).first
  end

  protected

  def same_deal
    Deal.where(account: account, type_cd: type_cd)
  end

  def check_prev_user
    previous_deal = prev_deal

    return if previous_deal.nil? || previous_deal.user != user

    errors.add(:base, 'Cant make deal with same user for same account')
  end

  def check_prev_enabled
    previous_deal = prev_deal

    return if previous_deal.nil? || previous_deal.disabled?

    errors.add(:base, 'Cant make deal if previous_deal enabled')
  end

  def dont_destroy_with_user
    return false if user.present?
  end

  def cant_disable_without_user
    errors.add(:disabled, 'Cant set disabled without user') if disabled? && user.nil?
  end
end

app/models/game.rb
# PS4 Game
class Game
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String

  mount_uploader :cover, CoverUploader

  has_and_belongs_to_many :accounts

  validates :title, presence: true, uniqueness: true

  def self.by_letter(letter)
    Game.where(title: Regexp.new("^#{letter}", true)).asc(:title).all
  end

  def self.not_in_account(account)
    Game.not_in(id: account.game_ids).all
  end
end

app/models/payment.rb
# Balance payments
class Payment
  include Mongoid::Document
  include Mongoid::Timestamps

  field :value, type: Integer

  embedded_in :user

  validates :value, presence: true
end

app/models/user.rb
# User class
class User
  include Mongoid::Document
  authenticates_with_sorcery!

  # login and email fields set in sorcery
  field :admin, type: Boolean, default: false

  embeds_many :payments do
    def total
      sum(:value)
    end
  end

  has_many :deals, before_add: :check_balance, before_remove: :do_not_remove do
    def total
      sum(:price)
    end
  end

  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }, presence: true, uniqueness: true
  validates :login, presence: true, length: { minimum: 3, maximum: 30 }, format: { with: /\A\w+\Z/ }, uniqueness: true

  validates :password, length: { minimum: 3 }, on: :create
  validates :password, confirmation: true, on: :create
  validates :password_confirmation, presence: true, on: :create

  def balance
    payments.total - deals.total
  end

  protected

  def check_balance(deal)
    fail InsufficientFunds.new, 'Недостаточно средств' if balance < deal.price
  end

  def do_not_remove(_)
    fail CantRemoveDealFromUser.new, 'У пользователя нельзя удалить сделку'
  end
end

class InsufficientFunds < StandardError
end

class CantRemoveDealFromUser < StandardError
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :require_login
  before_filter :find_account, only: [:buy, :checkout]
  before_filter :find_last_deal, only: [:buy, :checkout]

  def buy
  end

  def checkout
  end

  protected

  def find_account
    @account = Account.find(params[:id])
  end

  def find_last_deal
    @deal = @account.last_deal(params[:type])
  end
end

app/controllers/admin/accounts_controller.rb
# Accounts admin interface
class Admin::AccountsController < AdminController
  inherit_resources

  custom_actions resource: [:add_game, :add_deal, :remove_deal]

  def add_game
    add_game! do
      @game = Game.find(params[:game_id])
      @account.games << @game
      return redirect_to admin_account_path(@account)
    end
  end

  def add_deal
    add_deal! do
      @account.deals.create(params.permit(:price, :type))
      return redirect_to admin_account_path(@account)
    end
  end

  def remove_deal
    remove_deal! do
      @deal = Deal.find(params[:deal_id])
      @deal.destroy
      return redirect_to admin_account_path(@account)
    end
  end

  protected

  def permitted_params
    params.permit!
  end
end

app/controllers/admin/games_controller.rb
# Games admin interface
class Admin::GamesController < AdminController
  inherit_resources

  # def create
  #   create! { admin_games_path }
  # end

  # def update
  #   update! { admin_games_path }
  # end

  protected

  def permitted_params
    params.permit!
  end
end

app/controllers/admin_controller.rb
# Admin class
class AdminController < ApplicationController
  before_filter :require_login
  before_filter :admin_check

  protected

  def admin_check
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    account_ids = Deal.where(disabled: false).pluck(:account_id)
    @accounts = Account.where(:_id.in => account_ids)
  end
end

app/controllers/user_sessions_controller.rb
# User Sessions
class UserSessionsController < ApplicationController

  before_filter :check_authenticated_user, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = login(params[:login], params[:password])
    if @user
      redirect_back_or_to :root, notice: 'Login successful'
    else
      @login_error = true
      render :new
    end
  end

  def destroy
    logout
    redirect_to :root, notice: 'Logged out!'
  end

  protected

  def check_authenticated_user
    redirect_to :root if logged_in?
  end
end

app/controllers/users_controller.rb
# Users
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_back_or_to :root, notice: 'User created'
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:login, :email, :password, :password_confirmation)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin/accounts_helper.rb
module Admin::AccountsHelper
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/accounts/_account.html.slim
.panel.panel-default.account
  .panel-body
    = render account.games
    - if logged_in?
      h4 Купить аккаунт
      ul
        - (1..3).each do |type|
          - last_deal = account.last_deal(type)
          - if last_deal
            li
              = link_to buy_account_path(account, type), class: 'btn btn-success'
                | П#{type}: #{account.last_deal(type).price} руб.
    - else
      p Для покупки аккаунта вам нужно #{link_to 'зарегистрироваться', registration_path}

app/views/accounts/buy.html.slim
.container
  .page-header
    h1
      | Покупка аккаунта
  .row style="margin-top: 25px;"
    = render @account
  h2 Покупка аккаунта П#{params[:type]}
  p Цена: #{@deal.price}

app/views/accounts/checkout.html.slim
<h1>Accounts#checkout</h1>
<p>Find me in app/views/accounts/checkout.html.erb</p>

app/views/admin/accounts/_account.html.slim
tr
  td
    | ##{account_counter + 1}
  td
    = account.email
  td
    = account.games.pluck(:title).join(', ')
  td
    = link_to 'посмотреть', admin_account_path(account)
    | ,
    = link_to 'редактировать', edit_admin_account_path(account)
    | ,
    = link_to 'удалить', admin_account_path(account), method: :delete

app/views/admin/accounts/_deals.html.slim
h4
  = title
= render @account.deals.by_type(type)
- if @account.can_sell?(type)
  .panel.panel-info
    .panel-heading Выставить на продажу
    .panel-body
      = form_tag add_deal_admin_account_path(type: "p#{type}"), method: :post, html: {role: 'form'} do
        fieldset
          .form-group
            = label_tag :price, 'Цена', class: 'col-md-4 control-label'
            .col-md-4
              = text_field_tag :price, '', class: "form-control"
          .form-group
            .col-md-8
              = submit_tag 'Выставить на продажу', class: 'btn btn-primary'

app/views/admin/accounts/_form.html.slim
= form_for [:admin, @account], html: { class: 'form-horizontal' } do |f|
  fieldset
    .form-group
      = f.label :email, 'Почта', class: 'col-md-4 control-label'
      .col-md-4
        = f.text_field :email, class: 'form-control input-md', placeholder: 'Почта', required: true
    .form-group
      = f.label :email_password, 'Пароль от почты', class: 'col-md-4 control-label'
      .col-md-4
        = f.text_field :email_password, class: 'form-control input-md', placeholder: 'Пароль от почты', required: true
    .form-group
      = f.label :password, 'Пароль PSN', class: 'col-md-4 control-label'
      .col-md-4
        = f.text_field :password, class: 'form-control input-md', placeholder: 'Пароль PSN', required: true
    .form-group
      label class="col-md-4"
      .col-md-8
        = f.submit 'Сохранить', class: 'btn btn-success'
        = link_to 'Отмена', admin_accounts_path, class: 'btn btn-info', style: 'margin-left: 15px;'

app/views/admin/accounts/edit.html.slim
.container
  ol.breadcrumb
    li
      = link_to 'Аккаунты', admin_accounts_path
    li.active Редактирование аккаунта #{@account.email}

  = render 'form'

app/views/admin/accounts/index.html.slim
.container
  ol.breadcrumb
    li.active Аккаунты

  div style="margin: 20px 0 25px"
    = link_to 'Добавить аккаунт', new_admin_account_path, class: 'btn btn-info'

  table.table
    tr
      th #
      th Email
      th Игры
      th
    = render @accounts

app/views/admin/accounts/new.html.slim
.container
  ol.breadcrumb
    li
      = link_to 'Аккаунты', admin_accounts_path
    li.active Добавление аккаунта

  = render 'form'

app/views/admin/accounts/show.html.slim
.container
  ol.breadcrumb
    li
      = link_to 'Аккаунты', admin_accounts_path
    li.active #{@account.email}

  h3 #{@account.email}
  ul
    li дата создания: #{@account.created_at}
    - if @account.created_at != @account.updated_at
      li последнее обновление: #{@account.created_at}
    li пароль от почты: #{@account.email_password}
    li пароль PSN: #{@account.password}

  h3 Игры
  .row style="margin-top: 25px;"
    = render partial: 'games/game', collection: @account.games

  - if Game.count > @account.games.count
    .panel.panel-info
      .panel-heading Добавить игру в аккаунт
      .panel-body
        = form_tag add_game_admin_account_path, method: :post, html: {role: 'form'} do
          fieldset
            .form-group
              = label_tag :game_id, 'Игра', class: 'col-md-4 control-label'
              .col-md-4
                = select_tag :game_id, options_from_collection_for_select(Game.not_in_account(@account), 'id', 'title'), class: "form-control"
            .form-group
              .col-md-8
                = submit_tag 'Добавить', class: 'btn btn-primary'

  h3 Владельцы

  - (1..3).each do |type|
    = render partial: 'deals', locals: { title: "П#{type}", type: type }

app/views/admin/deals/_deal.html.slim
.deal class="#{'enabled btn btn-warning' unless deal.disabled? }"
  | Цена: #{deal.price} руб.
  - if deal.user
    | Пользователь: #{deal.user.login}
  = link_to remove_deal_admin_account_path(@account, deal), method: :delete, data: {confirm: 'Удалить предложение с сайта?'}
    span.glyphicon.glyphicon-remove

app/views/admin/games/_form.html.slim
= form_for [:admin, @game], html: { class: 'form-horizontal' } do |f|
  fieldset
    .form-group
      = f.label :cover, 'Обложка', class: 'col-md-4 control-label'
      .col-md-4
        - if @game.cover.present?
          = image_tag @game.cover.thumb, style: 'margin-bottom: 10px;'
        = f.file_field :cover, class: 'input-file'
    .form-group
      = f.label :title, 'Заголовок', class: 'col-md-4 control-label'
      .col-md-4
        = f.text_field :title, class: 'form-control input-md', placeholder: 'Название', required: true
    .form-group
      label class="col-md-4"
      .col-md-8
        = f.submit 'Сохранить', class: 'btn btn-success'
        = link_to 'Отмена', admin_games_path, class: 'btn btn-info', style: 'margin-left: 15px;'

app/views/admin/games/_game.html.slim
tr
  td
    | ##{game_counter + 1}
  td
    = link_to image_tag(game.cover.thumb), admin_game_path(game)
  td
    = link_to game.title, admin_game_path(game)
  td
    = link_to 'редактировать', edit_admin_game_path(game)
    | ,
    = link_to 'удалить', admin_game_path(game), method: :delete

app/views/admin/games/edit.html.slim
.container
  ol.breadcrumb
    li
      = link_to 'Игры', admin_games_path
    li.active Редактирование игры

  = render 'form'

app/views/admin/games/index.html.slim
.container
  ol.breadcrumb
    li.active Игры

  div style="margin: 20px 0 25px"
    = link_to 'Добавить игру', new_admin_game_path, class: 'btn btn-info'

  table.table
    = render @games

app/views/admin/games/new.html.slim
.container
  ol.breadcrumb
    li
      = link_to 'Игры', admin_games_path
    li.active Добавление игры

  = render 'form'

app/views/admin/games/show.html.slim
.container
  ol.breadcrumb
    li
      = link_to 'Игры', admin_games_path
    li.active
      = @game.title

  = render partial: 'games/game', locals: {game: @game}
  ul.game-info
    li Дата добавления: #{@game.created_at}
    li Последнее обновление: #{@game.updated_at}
  = link_to 'редактировать', edit_admin_game_path(@game)

.container
  h3 Аккаунты с игрой
  table.table
    = render @game.accounts

app/views/games/_game.html.slim
div style="width: 200px; text-align: center; float: left;"
  article.ps4.case
    div
      .img
        = image_tag 'ps4-topbar-160.png'
        = image_tag game.cover.thumb
  = game.title
  - if defined?(with_prices)
    ul.prices
      li П1 - от 300 рублей
      li П2 - от 500 рублей
      li П3 - от 900 рублей

app/views/index/index.html.slim
.container
  .page-header
    h1
      | Аккаунты на продаже
  .row style="margin-top: 25px;"
    = render @accounts, with_prices: true

app/views/layouts/admin.html.slim
doctype html
html
  head
    title Playtrade

    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-default role="navigation"
      .container-fluid
        - # Brand and toggle get grouped for better mobile display
        .navbar-header
          button.navbar-toggle type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'PlayTrade.ru', root_path, class: 'navbar-brand'
        - # Collect the nav links, forms, and other content for toggling
        .collapse.navbar-collapse#bs-example-navbar-collapse-1
          ul.nav.navbar-nav
            li class="#{'active' if params[:controller] == 'admin/games'}"
              = link_to 'Игры', admin_games_path
            li class="#{'active' if params[:controller] == 'admin/accounts'}"
              = link_to 'Аккаунты', admin_accounts_path
          ul.nav.navbar-nav.navbar-right
            li
              = link_to 'Выйти', destroy_session_path
    = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title Playtrade

    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-default role="navigation"
      .container-fluid
        - # Brand and toggle get grouped for better mobile display
        .navbar-header
          button.navbar-toggle type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'PlayTrade.ru', root_path, class: 'navbar-brand'
        - # Collect the nav links, forms, and other content for toggling
        .collapse.navbar-collapse#bs-example-navbar-collapse-1
          ul.nav.navbar-nav
            li class="#{'active' if params[:controller] == 'index'}"
              = link_to 'Главная', root_path
          /   li
          /     a href="#" Аукцион
          /   li
          /     a href="#" Игры
          / form.navbar-form.navbar-left role="search"
          /   .form-group
          /     input.form-control type="text" placeholder="Поиск по названию игры"
          /   button.btn.btn-default type="submit" Искать
          ul.nav.navbar-nav.navbar-right
            - if logged_in?
              - if current_user.admin?
                  li
                    = link_to 'Админка', admin_games_path
              li class="dropdown"
                a.dropdown-toggle href="#" data-toggle="dropdown"
                  | Меню
                  span.caret
                ul.dropdown-menu role="menu"
                  li
                    a href="#" Профиль
                  li
                    a href="#" Личные сообщения
                  li
                    a href="#" Настройки
                  li.divider
                  li
                    = link_to 'Выйти', destroy_session_path
            - else
              li class="#{'active' if params[:controller] == 'user_sessions'}"
                = link_to 'Войти', new_session_path
              li class="#{'active' if params[:controller] == 'users' && params[:action] == 'new'}"
                = link_to 'Зарегистрироваться', registration_path
    = yield

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.slim
.container
  .row style='margin-top:20px'
    .col-xs-12.col-sm-8.col-md-6.col-sm-offset-2.col-md-offset-3
      = form_tag create_session_path, method: :post, role: 'form'
        fieldset
          h2 Вход на сайт
          - if @login_error
            .alert.alert-warning role='alert'
              strong Ошибка!
              |  Логин или пароль неверные. Попробуйте еще раз, пожалуйста!
          hr.colorgraph
          .form-group
            = text_field_tag :login, '', placeholder: 'Логин', class: 'form-control input-lg'
          .form-group
            = password_field_tag :password, '', placeholder: 'Пароль', class: 'form-control input-lg'
          span.button-checkbox
            button.btn type='button' data-color='info' Запомнить меня
            = check_box_tag :remember_me, 1, true, class: 'hidden'
            / a.btn.btn-link.pull-right href='#' Забыли пароль?
          hr.colorgraph
          .row
            .col-xs-6.col-sm-6.col-md-6
              = submit_tag 'Вход', class: 'btn btn-lg btn-success btn-block'
            .col-xs-6.col-sm-6.col-md-6
              = link_to 'Регистрация', registration_path, class: 'btn btn-lg btn-primary btn-block'

app/views/users/new.html.slim
.container
  .row style='margin-top:20px'
    .col-xs-12.col-sm-8.col-md-6.col-sm-offset-2.col-md-offset-3
      = form_for @user, url: register_path, method: :post, role: 'form' do |f|
        fieldset
          h2 Регистрация
          - if @user.errors.any?
            - @user.errors.each do |field, msg|
              .alert.alert-warning role='alert'
                strong #{field}
                = msg
          hr.colorgraph
          .form-group
            = f.text_field :login, placeholder: 'Логин', class: 'form-control input-lg'
          .form-group
            = f.email_field :email, placeholder: 'Email', class: 'form-control input-lg'
          .form-group
            = f.password_field :password, placeholder: 'Пароль', class: 'form-control input-lg'
          .form-group
            = f.password_field :password_confirmation, placeholder: 'Подтверждение пароля', class: 'form-control input-lg'
          hr.colorgraph
          .row
            .col-xs-6.col-sm-6.col-md-6
              = submit_tag 'Зарегистрироваться', class: 'btn btn-lg btn-success btn-block'
            .col-xs-6.col-sm-6.col-md-6
              = link_to 'Уже есть аккаунт', new_session_path, class: 'btn btn-lg btn-primary btn-block'